### ISSUE TITLE
Add alternative titles to metadata

### ISSUE THREAD

**Issue by ncwmail** [standardebooks/edgar-wallace_the-square-emerald#1]
_The Square Emerald_ was also published under the titles  _The Girl from Scotland Yard_ and _The Woman_ as per Edgar Wallace bibliography(https://en.wikipedia.org/wiki/Edgar_Wallace) in Wikipedia .

**Comment by acabal** [comment]
I added The Woman but Wikipedia makes it see like The Girl from Scotland Yard is a separate book.
